byte waitForByte();
void sendError(byte commandId, byte errorCode);
void debugLEDBlink();
void debugEcho();
void openWritingPipe();
void openReadingPipe();
void write();
void tx(byte payloadSize);
void readRadio();
void processCommand();
