byte waitForByte();
void sendError(byte code);
void debugLEDBlink();
void debugEcho();
void openWritingPipe();
void openReadingPipe();
void write();
void tx();
void readRadio();
void processCommand();
